first-app/first-app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("webdjango/",include("webdjango.urls")),
    path("taskapp/",include("taskapp.urls")),
    path("newyear/",include("newyear.urls")) 
    
]

first-app/newyear/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("",views.index,name="index")
]

first-app/taskapp/urls.py
from django.urls import path
from . import views

app_name = "taskapp"
urlpatterns = [
    path("",views.index, name = "index"),
    path("add",views.add, name = "add"),
    path("remove",views.remove, name = "remove"),
]

first-app/webdjango/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name = "index"),
    path("<str:name>",views.greet,name = "greet"),
    path("brian",views.brian,name = "brian"),
    path("david",views.david,name = "david"),
    
]

first-app/newyear/models.py
from django.db import models

# Create your models here.

first-app/taskapp/models.py
from django.db import models

# Create your models here.

class Model(models.Model):

    firstname = models.CharField(max_length=64)
    lastname = models.CharField(max_length=64)
    age = models.IntegerField()

first-app/webdjango/models.py
from django.db import models

# Create your models here.

first-app/newyear/views.py
from django.http import HttpResponse
from django.shortcuts import render

import datetime
# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.month == 1 and now.day == 1
    })

first-app/taskapp/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.

#client side validation of data
class NewTaskForm(forms.Form):
    task = forms.CharField(label="")

class RemoveTaskForm(forms.Form):
    task = forms.CharField(label="")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    else:
        request.session["tasks"]


    return render(request,"taskapp/index.html",{
        "tasks" :request.session["tasks"]
        })

def add(request):

    # server side validation
    if request.method == 'POST':
        form = NewTaskForm(request.POST)

        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("taskapp:index"))
        else:
            return render(request,"taskapp/add.html",{
        "form" : form.capitalize()
            })
        
    return render(request,"taskapp/add.html",{
        "form" : NewTaskForm()
    })


def remove(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            if task in request.session["tasks"]:
                request.session["tasks"].remove(task)
                request.session.modified = True  # Save changes to the session
            return HttpResponseRedirect(reverse("taskapp:index"))
        else:
            return render(request, "taskapp/add.html", {
                "form": form
            })
    return render(request, "taskapp/remove.html", {
        "form": RemoveTaskForm()
    })

# def play(request):

#     musics = [
#         "hillsong.mp3",
#         "Notafraid.mp3",
#         "overcome.mp3",
#         "Shemipeace.mp3",
#         "Theecember.mp3"
#     ]

#     return render(request,"taskapp/play.html",{
#         "musics" :musics
#     })

first-app/webdjango/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,"webdjango/web.html")


def brian(request):
    return HttpResponse("Hello, brian")

def david(request):
    return HttpResponse("Hello, david")

def greet(request,name):
    return render(request,"webdjango/greet.html",{"name":name.capitalize()})

first-app/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'newyear/style.css' %}" rel="stylesheet">
    <title>New Year </title>
</head>
<body>
    {% if newyear %}
        <h1>Yes</h1>
    {% else %}
        <h2>No</h2>
    {% endif %}
</body>
</html>

first-app/taskapp/templates/taskapp/add.html
{% extends 'taskapp/layout.html' %}

{% block body %}
    <h1>Add Task to the list</h1>
    <form action = "{% url 'taskapp:add' %}" method="post"> 
        {% csrf_token %}
        {{form}}
        <input class = "submit" type="submit">
    </form>

    <button><a href="{% url 'taskapp:index' %}">Return</a></button>

{% endblock %}

first-app/taskapp/templates/taskapp/index.html
{% extends 'taskapp/layout.html' %}

{% block  body%}
    
    <div class="task">
        <h1>Tasks registered</h1>
        <i class="fa fa-calendar" aria-hidden="true"></i>
    </div>
        <ul>
            {% for task in tasks%}
                <li>{{task}}</li>
            {% endfor %}
        </ul>

        
   
   


    <button><a href="{% url 'taskapp:add' %}">Add</a></button>

    <button><a href="{% url 'taskapp:remove' %}">Remove</a></button>

    <button class="linked"><a href="https://tharcisse.netlify.app/">Visit me online</a></button>

{% endblock body%}

first-app/taskapp/templates/taskapp/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Tasks</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href="{% static 'taskapp/task.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<style>
    body{
        position: relative;
        position: absolute;
        justify-content: center;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        align-items: center;
        background-color: black;
        color: aliceblue;
        left: 35%;
    }
    .task{
        display: flex;
        flex-wrap: nowrap;
        flex-direction: row;
        flex-grow: 2;
        flex-basis: 200px;
    }

    .task .fa{
        position: relative;
        color: orange;
        border-radius: 6px;
        left: 10%;
        font-size: 80px;
        height: 10px;
        
    }

    h1{
        position: relative;
        color:bisque;
        right: 5%;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    h1:hover{
        position: relative;
        font-size: 20px;
        left: 0%;
        
    }
    .submit{
        position: relative;
        text-decoration: none;
        border: none;
        border-radius: 5px;
        padding: 6px;
        background-color: aqua;
        left : 20px;    

    }
    input{
        position: relative;
        padding: 4px;
        border: none;
        border-color: default_if_none;
        border-radius:5px ;

    }

    a,button{
        position: relative;
        flex-direction: column;
        background-color: aqua;
        border: none;
        padding: 4px;
        margin: 6px;
        border-radius: 5px;
        text-decoration: none;
       
   }

   button{
    position: relative;
    margin: 30px;
    right: 15%;
    justify-content: center;
    place-items: center;
   }

   button.linked{
    color: darkslateblue;
   }

</style>
<body>
    {% block  body%}
    {% endblock  %}
    
</body>
</html>

first-app/taskapp/templates/taskapp/play.html
"""

{% load static %}

{% block body %}

{% for music in musics %}  
<audio controls>  
    <source src="{% static 'startapp/'|add:music %}" type="audio/mpeg">
</audio>  
{% endfor %}  

{% endblock  %}

"""

first-app/taskapp/templates/taskapp/remove.html
{% extends 'taskapp/layout.html' %}

{% block body %}
    <h1>Remove Task to the list</h1>
    <form action = "{% url 'taskapp:remove' %}" method="post"> 
        {% csrf_token %}
        {{form}}
        <input class="submit" type="submit">
    </form>

    <button><a href="{% url 'taskapp:index' %}">Return</a></button>

{% endblock %}

first-app/webdjango/templates/webdjango/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greet</title>
</head>

<style>
    body{
        background-color: rgb(7, 7, 31);
        color: azure;
    }
</style>
<body>
    <h1>Welcome back, {{name}}</h1>
</body>
</html>

first-app/webdjango/templates/webdjango/web.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href="index.css">
    <title>Music Player</title>
</head>
<style>
    body{
        background-color: rgb(33, 28, 36);
        color: azure;
    }
</style>
<body>
    <!-- <form action="login" class="form"> -->
        <input type="text" name="name" class="firstname" placeholder="First name">
        <br><br>
        <input type="password" name="password" class="password" placeholder="Password">
        <br><br>
        <input type="submit" name="button" class="btn">
        <h1>Hello Maniga , {{firstname}}</h1>
    </form>
</body>
</html>